In [1]:
#importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("TREE.csv") #Reading CSV File 

In [4]:
df.head() #Calling head of csv file which we loaded

company                job education  sal_more_than_50K
0     TCS  PROJECT EXECUTIVE    B.TECH                  0
1     TCS  PROJECT EXECUTIVE    M.TECH                  0
2     TCS    PROJECT MANAGER    B.TECH                  1
3     TCS    PROJECT MANAGER    M.TECH                  1
4     TCS         PROGRAMMER    B.TECH                  0

In [9]:
df.isnull().sum()

company              0
job                  0
education            0
sal_more_than_50K    0
dtype: int64

In [24]:
df_car = df[["company","job","education"]]

In [25]:
df_car


company                job education
0         TCS  PROJECT EXECUTIVE    B.TECH
1         TCS  PROJECT EXECUTIVE    M.TECH
2         TCS    PROJECT MANAGER    B.TECH
3         TCS    PROJECT MANAGER    M.TECH
4         TCS         PROGRAMMER    B.TECH
5         TCS         PROGRAMMER    M.TECH
6     INFOSYS  PROJECT EXECUTIVE    M.TECH
7     INFOSYS         PROGRAMMER    B.TECH
8     INFOSYS    PROJECT MANAGER    B.TECH
9     INFOSYS    PROJECT MANAGER    M.TECH
10  MICROSOFT  PROJECT EXECUTIVE    B.TECH
11  MICROSOFT  PROJECT EXECUTIVE    M.TECH
12  MICROSOFT    PROJECT MANAGER    B.TECH
13  MICROSOFT    PROJECT MANAGER    M.TECH
14  MICROSOFT         PROGRAMMER    B.TECH
15  MICROSOFT         PROGRAMMER    M.TECH

In [26]:
df_num = df[["sal_more_than_50K"]]

In [27]:
df_num

sal_more_than_50K
0                   0
1                   0
2                   1
3                   1
4                   0
5                   1
6                   0
7                   0
8                   0
9                   1
10                  1
11                  1
12                  1
13                  1
14                  1
15                  1

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le = LabelEncoder()

In [31]:
df_car = df_car.apply(le.fit_transform)


In [32]:
df_car

company  job  education
0         2    1          0
1         2    1          1
2         2    2          0
3         2    2          1
4         2    0          0
5         2    0          1
6         0    1          1
7         0    0          0
8         0    2          0
9         0    2          1
10        1    1          0
11        1    1          1
12        1    2          0
13        1    2          1
14        1    0          0
15        1    0          1

In [33]:
df_final = pd.concat([df_num,df_car],axis=1)

In [34]:
df_final

sal_more_than_50K  company  job  education
0                   0        2    1          0
1                   0        2    1          1
2                   1        2    2          0
3                   1        2    2          1
4                   0        2    0          0
5                   1        2    0          1
6                   0        0    1          1
7                   0        0    0          0
8                   0        0    2          0
9                   1        0    2          1
10                  1        1    1          0
11                  1        1    1          1
12                  1        1    2          0
13                  1        1    2          1
14                  1        1    0          0
15                  1        1    0          1

In [37]:
x=df_final[["company","job","education"]]

In [38]:
x

company  job  education
0         2    1          0
1         2    1          1
2         2    2          0
3         2    2          1
4         2    0          0
5         2    0          1
6         0    1          1
7         0    0          0
8         0    2          0
9         0    2          1
10        1    1          0
11        1    1          1
12        1    2          0
13        1    2          1
14        1    0          0
15        1    0          1

In [39]:
y=df_final["sal_more_than_50K"]

In [40]:
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: sal_more_than_50K, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [47]:
from sklearn import tree


In [48]:
model=tree.DecisionTreeClassifier()

In [49]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [50]:
model.score(x,y)

0.8125

In [51]:
model.score(x_train,y_train)

1.0

In [52]:
model.score(x_test,y_test)

0.5

In [53]:
pred=model.predict(x_test)

In [54]:
val=model.predict([[2,1,0]])
val

array([1], dtype=int64)

In [55]:
val1=model.predict([[2,2,0]])
val1

array([1], dtype=int64)

In [56]:
val2=model.predict([[0,2,0]])
val2

array([0], dtype=int64)